language: cpp
compiler:
  - g++
os:
  - linux
dist: "trusty"  
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
install:
  - sudo rm /usr/bin/g++
  - sudo apt-get install -y software-properties-common git make libssl-dev g++-4.9
  - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
git:
  depth: 1
branches:
  only:
    - master
script:
  - cd trunk/build
  - make
